CFG_KEY_VERSION = 'Version'
CFG_KEY_LOGGING = 'Logging'
CFG_KEY_VIDEO = "Video"

CFG_LOGGING_KEY_DEFAULT_TYPE = 'DefaultLogType'
CFG_LOGGING_KEY_EVENT_RULES = 'EventLoggingRules'
CFG_LOGGING_KEY_BUFFERSIZE = 'BufferSize'

DEBUG_INFO_KEY_CONTROLLER_NAME = "ControllerName"
DEBUG_INFO_KEY_EVENT_TIME = "EventTime"

CFG_LOGGING_DEFAULTLOGTYPE_CONSOLE = "console"
CFG_LOGGING_DEFAULTLOGTYPE_FILE = "file"

CFG_VIDEO_WINDOWX = "WindowX"
CFG_VIDEO_WINDOWY = "WindowY"

STATE_STARTUP = "Starting"
STATE_INITIALIZING = "Initializing"
STATE_RUNNING = "Running"

CONTROLLER_LOGGING = "LogController"
CONTROLLER_INPUT = "InputController"
CONTROLLER_VIEW_INIT = "ViewInitializationController"
CONTROLLER_DUNGEON_COMMAND = "DungeonCommandController"
CONTROLLER_VIEW_DUNGEON = "DungeonViewController"
CONTROLLER_DUNGEON_MODEL = "DungeonModelController"

INPUTSTATE_OPEN = 'OPEN'
INPUTSTATE_MOUSEDOWN = 'MOUSEDOWN'

INPUTEVENT_MOUSEDOWN = 'MOUSEDOWN'
INPUTEVENT_MOUSEUP = 'MOUSEUP'
INPUTEVENT_MOUSEMOVE = 'MOUSEMOVE'
INPUTEVENT_KEYDOWN = 'KEYDOWN'
INPUTEVENT_KEYUP =  'KEYUP'